mysql:
  dns: root:123456@tcp(192.168.229.130:3306)/fil_db?charset=utf8mb4&parseTime=True&loc=Local

env: local

datasource:
  host: 192.168.83.109
  port: 3306
  database: fil_db
  username: ethan
  password: Ethan@123

datasource-local:
  host: 127.0.0.1
  port: 3306
  database: fil_db
  username: root
  password: 123456!

nodes: []

monitor:
  host: localhost
  port: 8083

redis:
  host: 127.0.0.1
  port: 6379
  